version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vybes-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - vybes-net

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    networks:
      - vybes-net

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # For monitoring
    networks:
      - vybes-net

  vybes-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
      - minio
      - nats
    env_file:
      - .env
    environment:
      # Override .env values to point to Docker services
      MONGO_URI: mongodb://mongo:27017
      REDIS_ADDR: redis:6379
      MINIO_ENDPOINT: minio:9000
      NATS_URL: nats://nats:4222
    networks:
      - vybes-net

volumes:
  mongo-data:
  minio-data:

networks:
  vybes-net:
    driver: bridge