version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: vybes-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    image: redis:7-alpine
    container_name: vybes-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # NATS
  nats:
    image: nats:2-alpine
    container_name: vybes-nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"

  # API Service
  api:
    build: .
    container_name: vybes-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      - MONGO_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${DB_NAME}?authSource=admin
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - WALLET_ENCRYPTION_KEY=${WALLET_ENCRYPTION_KEY}
      - ETH_RPC_URL=${ETH_RPC_URL}
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - NATS_URL=nats://nats:4222
      # R2 Configuration
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_POSTS_BUCKET=${R2_POSTS_BUCKET}
      - R2_STORIES_BUCKET=${R2_STORIES_BUCKET}
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
      - nats

volumes:
  mongodb_data:
  redis_data: