version: '3.8'

services:
  # NATS
  nats:
    image: nats:2-alpine
    container_name: vybes-nats
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222"

  # API Service
  api:
    build: .
    container_name: vybes-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - WALLET_ENCRYPTION_KEY=${WALLET_ENCRYPTION_KEY}
      - ETH_RPC_URL=${ETH_RPC_URL}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=0
      - NATS_URL=nats://nats:4222
      # R2 Configuration
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_POSTS_BUCKET=${R2_POSTS_BUCKET}
      - R2_STORIES_BUCKET=${R2_STORIES_BUCKET}
    env_file:
      - .env
    depends_on:
      - nats