apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vybes

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongo-persistent-volume.yaml
  - minio-persistent-volume.yaml
  - mongo-deployment.yaml
  - redis-deployment.yaml
  - minio-deployment.yaml
  - nats-deployment.yaml
  - vybes-api-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: vybes
  app.kubernetes.io/instance: production
  app.kubernetes.io/version: "1.0.0"