apiVersion: apps/v1
kind: Deployment
metadata:
  name: vybes-api
  namespace: vybes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vybes-api
  template:
    metadata:
      labels:
        app: vybes-api
    spec:
      containers:
      - name: vybes-api
        image: vybes-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: APP_ENV
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: APP_PORT
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: MONGO_URI
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: REDIS_ADDR
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: MINIO_ENDPOINT
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: vybes-config
              key: NATS_URL
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: vybes-secrets
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: vybes-secrets
              key: MINIO_SECRET_KEY
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: vybes-secrets
              key: JWT_SECRET
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: vybes-secrets
              key: API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vybes-api-service
  namespace: vybes
spec:
  selector:
    app: vybes-api
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP